[package]
edition = "2024"
name = "howlto"
readme = "README.md"
version = "0.1.0"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
axum = {version = "0.8.7", optional = true}
clap = {version = "4.5.53", features = ["derive"]}
color-eyre = "0.6.5"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
shellexpand = "3.1.1"
thiserror = "2.0.17"
tokio = {version = "1.48.0", features = ["macros", "rt-multi-thread", "net", "sync", "fs", "io-util"]}
tokio-stream = "0.1"
toml = "0.9.8"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
uuid = {version = "1.11", features = ["v4"]}

[[bin]]
name = "mocker"
path = "src/bin/mocker.rs"
required-features = ["mocker"]

[features]
default = []
mocker = ["dep:axum"]
